#' Render the report
#'
#' Render the Rmd report located at `report/report.Rmd` to the `report/` directory.
#' Also move and rename the generated report to the `results/reports/` directory.
#'
#' @return The path to the moved and renamed report file.
run_report <- function() {
  report_rmd_path <- fs::path("report", "report", ext = "Rmd")
  # Check if the report file exists
  if (!fs::file_exists(report_rmd_path)) {
    cli::cli_abort(
      c(
        "x" = "Report file {.path {report_rmd_path}} does not exist.",
        "i" = "Use {.fn create_report} to create the report first."
      )
    )
  }
  # Render the report to the ´report/´ directory
  report_path <- rmarkdown::render(
    input = report_rmd_path,
    output_format = "all",
    output_dir = "report",
    clean = TRUE,
    envir = new.env()
  )
  cli::cli_bullets(
    c(
      "v" = "Report rendered at {.path {report_path}}."
    )
  )
  # Move and rename the report to the results/reports/ directory
  moved_path <- move_rename_report(old_name = report_path)
}

#' Moves a report to a different location and rename it uniquely
#'
#' Move the report file generated by `run_report()` from the `reports/` directory to the
#' `results/reports/` directory, renaming it to include:
#' - the current date
#' - the project version (from the DESCRIPTION file)
#' - a unique identifier if a file with the same name already exists
#'
#' This function helps to archive reports systematically.
#'
#' @return The path to the moved and renamed report file.
#' @md
move_rename_report <- function(old_name = "report.docx") {
  # Check if the report file exists
  old_path <- fs::path("reports", old_name)
  if (!fs::file_exists(old_path)) {
    cli::cli_abort(
      c(
        "x" = "Report file {.path reports/report.docx} does not exist.",
        "i" = "Use {.fn run_report} to create the report first."
      )
    )
  }
  # Load project metadata from DESCRIPTION
  version <- desc::desc_get("Version")
  date <- format(Sys.Date(), "%Y_%m_%d")

  # Construct the new file name
  base_name <- paste(
    "report",
    date,
    paste0("v", gsub("\\.", "_", version)),
    sep = "_"
  )
  new_name <- fs::path(base_name, ext = fs::path_ext(old_name))

  # Ensure the results/reports directory exists
  check_dir_exists("results/reports")

  # Check for existing files and create a unique name if necessary
  counter <- 1
  final_name <- new_name
  while (fs::file_exists(final_name)) {
    new_base_name <- paste0(
      base_name,
      "_",
      sprintf("%03d", counter),
      fs::path_ext(name, TRUE)
    )
    final_name <- fs::path(new_base_name, ext = fs::path_ext(old_name))
    counter <- counter + 1
  }

  # Move and rename the report file
  new_path <- fs::path("results/reports", final_name)
  fs::file_move("reports/report.docx", new_path)

  cli::cli_bullets(
    c(
      "v" = "Report moved and renamed to {.path {new_path}}."
    )
  )

  return(new_path)
}
