#' Render the report
#'
#' Render the Rmd report located at `report/report.Rmd` to the `report/` directory.
#' Also move and rename the generated report to the `results/reports/` directory.
#'
#' @return The path to the moved and renamed report file.
#'
#' @export
run_report <- function() {
  report_rmd_path <- fs::path("report", "report", ext = "Rmd")
  # Check if the report file exists
  if (!fs::file_exists(report_rmd_path)) {
    cli::cli_abort(
      c(
        "x" = "Report file {.path {report_rmd_path}} does not exist.",
        "i" = "Use {.fn create_report} to create the report first."
      )
    )
  }
  # Render the report to the ´report/´ directory
  report_path <- rmarkdown::render(
    input = report_rmd_path,
    output_format = "all",
    output_dir = "report",
    clean = TRUE,
    envir = new.env()
  )
  cli::cli_alert_success("Report rendered at {.path {report_path}}.")
  # Move and rename the report to the results/reports/ directory
  moved_path <- move_rename_report(old_path = report_path)
}

#' Moves a report to a different location and rename it uniquely
#'
#' Move the report file generated by `run_report()` from the `reports/` directory to the
#' `results/reports/` directory, renaming it to include:
#' - the current date
#' - the project version (from the DESCRIPTION file)
#' - a unique identifier if a file with the same name already exists
#' This function helps to archive reports systematically.
#'
#' @param old_path The current path of the report file to be moved (with extension in the
#'     filename)
#'
#' @return The path to the moved and renamed report file.
#' @md
move_rename_report <- function(old_path) {
  # Check if the report file exists
  if (!fs::file_exists(old_path)) {
    cli::cli_abort(
      c(
        "x" = "Report file {.path {old_path}} does not exist.",
        "i" = "Use {.fn run_report} to create the report first."
      )
    )
  }

  # Define the paths and names of the new report files
  old_name <- fs::path_file(old_path)
  extension <- fs::path_ext(old_name)
  new_name <- build_report_name(extension = extension, counter = NULL)
  new_path <- fs::path("results/reports", new_name)

  # Ensure the results/reports directory exists
  check_dir_exists("results/reports")

  # Check for existing files and create a unique name if necessary
  counter <- 1
  while (fs::file_exists(new_path)) {
    new_name <- build_report_name(extension = extension, counter = counter)
    new_path <- fs::path("results/reports", new_name)
    counter <- counter + 1
  }

  # Move and rename the report file
  fs::file_move(old_path, new_path)

  cli::cli_alert_success("Copying report to {.file {fs::path_rel(new_path)}}.")
}

#' Build a report file name with date, version, and optional counter and extension
build_report_name <- function(extension, counter = NULL) {
  # Load project metadata from DESCRIPTION
  version <- desc::desc_get("Version")
  date <- format(Sys.Date(), "%Y_%m_%d")

  # Construct the new file name
  base_name <- paste(
    "report",
    date,
    paste0("v", gsub("\\.", "_", version)),
    sep = "_"
  )
  if (!is.null(counter)) {
    base_name <- paste0(base_name, "_", sprintf("%03d", counter))
  }
  new_name <- fs::path(base_name, ext = extension)

  return(new_name)
}
